name: GoldenFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.3
description: Plugin for GoldenFreedom, an all-op server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, Prozza, iDelRey, falceso, DarkGamingDronze, tylerhyperHD, Hockeyfan360, AwesomePinch, Alco_Rs11, reuben4545, botisz02]

# plugin.yml is no longer used to define commands.
