name: PumpkinFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.4
description: Plugin for PumpkinFreedom, an all-op server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, Prozza, iDelRey, falceso, DarkGamingDronze, tylerhyperHD, Hockeyfan360, AwesomePinch, Alco_Rs11, reuben4545, botisz02, FaZePamaaj]

# plugin.yml is no longer used to define commands.
